### ISSUE TITLE
Allow multiple output formats in one call.

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-labs/tern-action#11]
# Problem
Currently the workflow is limited to only one output format.

# Solution
Allow an array of output formats.

# Proposed format
```
name: build 
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@v1.0.0
        id: scan
        with:
          image: alpine:latest
          format: [yaml, spdx]
          output: alpine
      - uses: actions/upload-artifact@v2
        with:
          name: tern 
          path: ${{ steps.scan.outputs.files }} 
```
